//declaration and initilization
var price=100;
let fruit="mango";
const fruit_wieght=150

console.log(price);
console.log(price,typeof(price));
console.log(fruit);
console.log(fruit,typeof(fruit));
console.log(fruit_wieght,typeof(fruit_wieght));


//5 examples 
//try to write declare and initilize printing in console 10 functionality use 3 keywords
//door  
//locker
//mouse
//plug
//table
//self-invoking function


(function(){
    var ref=500;
    console.log(ref);
}())

// //Named Function
function nameOfFunction(){
    console.log("Named function");
}
nameOfFunction();

var arrowFuncton=()=>{
    console.log("this is arrow functon");
}
arrowFuncton();

//take 10 example tyrto write 10 let var const print in console fuction

//hogher order function

















